# --- !Ups

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "firstName" varchar not null,
  "lastName" varchar not null,
  "email" varchar not null
);

create table "passwords" (
    "userEmail" varchar not null primary key,
    "hasher" text not null,
    "hash" text not null,
    "salt" text
);

# --- !Downs

drop table "users" if exists;
drop table "passwords" if exists;
