# --- !Ups

create table "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "email" varchar not null,
  "firstName" varchar not null,
  "lastName" varchar not null,
  "roles" varchar not null
);

create table "passwords" (
    "userEmail" varchar not null primary key,
    "hasher" text not null,
    "hash" text not null,
    "salt" text
);

insert into "users" ("email", "firstName", "lastName", "roles")
    values ( 'admin@jogging.com', 'Admin', 'Admin', 'ADMIN' );
insert into "passwords"
    values ( 'admin@jogging.com',
            'bcrypt',
            '$2a$10$pjnp9/GDJxEv0tGYZRHpT.esEkQsfsq/z2TY3YpnoVpsOvzT4TE3m',
            null );

create table "records" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "userId" bigint not null,
    "date" timestamp with time zone not null,
    "distance" int not null,
    "duration" int not null,
    "locationLat" double not null,
    "locationLon" double not null,
    "temperature" varchar,
    "humidity" int,
    "windSpeed" varchar
);

create table "average_reports" (
    "id" bigint generated by default as identity(start with 1) not null primary key,
    "userId" bigint not null,
    "avgSpeed" double not null,
    "avgDistance" double not null,
    "date" timestamp with time zone not null
);

# --- !Downs

drop table "users" if exists;
drop table "passwords" if exists;
drop table "records" if exists;
drop table "average_reports" if exists;
